"""Added isRecurring field to Transactions

Revision ID: 2fb0d95a09d6
Revises: 732873934cce
Create Date: 2023-10-21 16:45:19.670541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb0d95a09d6'
down_revision: Union[str, None] = '732873934cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('isRecurring', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'isRecurring')
    # ### end Alembic commands ###
