"""Added auto-increment to UserParsedCategory id field

Revision ID: 36b205eb1713
Revises: 8750d20a1635
Create Date: 2023-10-28 02:40:12.857741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b205eb1713'
down_revision: Union[str, None] = '8750d20a1635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
