"""Changed frequncy fields to be two seperate fields: value and unit

Revision ID: 40093235e016
Revises: b4047d47a4d2
Create Date: 2023-10-21 17:26:29.062083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40093235e016'
down_revision: Union[str, None] = 'b4047d47a4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurringTransactions', sa.Column('frequency_value', sa.Integer(), nullable=True))
    op.add_column('recurringTransactions', sa.Column('frequency_unit', sa.String(length=50), nullable=True))
    op.drop_column('recurringTransactions', 'frequencyInMinutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurringTransactions', sa.Column('frequencyInMinutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('recurringTransactions', 'frequency_unit')
    op.drop_column('recurringTransactions', 'frequency_value')
    # ### end Alembic commands ###
