"""DB Init

Revision ID: 802d5f1a1709
Revises: 
Create Date: 2023-10-21 15:35:50.479635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database.models import db

# revision identifiers, used by Alembic.
revision: str = '802d5f1a1709'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('shouldGetScrapped', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('appUserCredentials',
    sa.Column('userEmail', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('identityDocumentNumber', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['userEmail'], ['user.email'], ),
    sa.PrimaryKeyConstraint('userEmail')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoryName', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userWarnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userEmail', sa.String(length=255), nullable=True),
    sa.Column('failedToScrape', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['userEmail'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('arn', sa.String(), nullable=False),
    sa.Column('userEmail', sa.String(length=255), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('transactionAmount', sa.Float(), nullable=True),
    sa.Column('paymentDate', sa.Date(), nullable=True),
    sa.Column('purchaseDate', sa.Date(), nullable=True),
    sa.Column('shortCardNumber', sa.String(length=4), nullable=True),
    sa.Column('merchantData', sa.JSON(), nullable=True),
    sa.Column('originalCurrency', sa.String(length=3), nullable=True),
    sa.Column('originalAmount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['category.id'], ),
    sa.ForeignKeyConstraint(['userEmail'], ['user.email'], ),
    sa.PrimaryKeyConstraint('arn')
    )
    op.create_table('userCategoryData',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('userEmail', sa.String(length=255), nullable=True),
    sa.Column('monthlyBudget', sa.Integer(), nullable=True),
    sa.Column('monthlySpending', sa.Integer(), nullable=True),
    sa.Column('monthlyAverage', sa.Integer(), nullable=True),
    sa.Column('isPinned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['category.id'], ),
    sa.ForeignKeyConstraint(['userEmail'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userParsedCategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chargingBusiness', sa.String(length=255), nullable=True),
    sa.Column('ownerEmail', sa.String(length=255), nullable=True),
    sa.Column('targetCategoryId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ownerEmail'], ['user.email'], ),
    sa.ForeignKeyConstraint(['targetCategoryId'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoryMonthlyAveragesHistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('monthlyAverage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['userCategoryData.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurringTransactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_arn', sa.String(), nullable=False),
    sa.Column('frequencyInMinutes', sa.Integer(), nullable=True),
    sa.Column('startDate', sa.Date(), nullable=True),
    sa.Column('scannedAt', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_arn'], ['transaction.arn'], ),
    sa.PrimaryKeyConstraint('id')
    )
    db.session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurringTransactions')
    op.drop_table('categoryMonthlyAveragesHistory')
    op.drop_table('userParsedCategory')
    op.drop_table('userCategoryData')
    op.drop_table('transaction')
    op.drop_table('userWarnings')
    op.drop_table('category')
    op.drop_table('appUserCredentials')
    op.drop_table('user')
    db.session.commit()
    # ### end Alembic commands ###
