"""Column name changes for the CategoryMonthlyAveragesHistory table

Revision ID: ba233b21f5f8
Revises: 4c3f20111936
Create Date: 2023-10-22 15:31:26.253889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba233b21f5f8'
down_revision: Union[str, None] = '4c3f20111936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoryMonthlyAveragesHistory', sa.Column('monthlyAverageDate', sa.Date(), nullable=True))
    op.add_column('categoryMonthlyAveragesHistory', sa.Column('monthlyAverageAmount', sa.Integer(), nullable=True))
    op.drop_column('categoryMonthlyAveragesHistory', 'date')
    op.drop_column('categoryMonthlyAveragesHistory', 'monthlyAverage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categoryMonthlyAveragesHistory', sa.Column('monthlyAverage', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('categoryMonthlyAveragesHistory', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('categoryMonthlyAveragesHistory', 'monthlyAverageAmount')
    op.drop_column('categoryMonthlyAveragesHistory', 'monthlyAverageDate')
    # ### end Alembic commands ###
