"""Initial migration

Revision ID: 227252270d0b
Revises: 
Create Date: 2023-11-18 13:38:51.025837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227252270d0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('fullName', sa.String(length=255), nullable=True),
    sa.Column('monthlyBudget', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('shouldGetScrapped', sa.Boolean(), nullable=True),
    sa.Column('lastTransactionsScanDate', sa.DateTime(), nullable=True),
    sa.Column('initialSetupDone', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('appUserCredentials',
    sa.Column('userEmail', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('identityDocumentNumber', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['userEmail'], ['user.email'], ),
    sa.PrimaryKeyConstraint('userEmail')
    )
    op.create_table('userCategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoryName', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('monthlyBudget', sa.Integer(), nullable=True),
    sa.Column('isPinned', sa.Boolean(), nullable=True),
    sa.Column('iconName', sa.String(length=50), nullable=True),
    sa.Column('colorCode', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userWarnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userEmail', sa.String(length=255), nullable=False),
    sa.Column('failedLoginCount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userEmail'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoryMonthlyAveragesHistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userCategoryId', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('averageAmount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userCategoryId'], ['userCategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('arn', sa.String(length=255), nullable=False),
    sa.Column('userEmail', sa.String(length=255), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('transactionAmount', sa.Float(), nullable=True),
    sa.Column('paymentDate', sa.DateTime(), nullable=True),
    sa.Column('purchaseDate', sa.DateTime(), nullable=True),
    sa.Column('shortCardNumber', sa.String(length=4), nullable=True),
    sa.Column('merchantData', sa.JSON(), nullable=True),
    sa.Column('originalCurrency', sa.String(length=3), nullable=True),
    sa.Column('originalAmount', sa.Float(), nullable=True),
    sa.Column('isRecurring', sa.Boolean(), nullable=True),
    sa.Column('isDeleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['userCategory.id'], ),
    sa.ForeignKeyConstraint(['userEmail'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userCategorySpending',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userEmail', sa.String(length=255), nullable=True),
    sa.Column('userCategoryId', sa.Integer(), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('spendingAmount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userCategoryId'], ['userCategory.id'], ),
    sa.ForeignKeyConstraint(['userEmail'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userCategorySpending_date'), 'userCategorySpending', ['date'], unique=False)
    op.create_table('userParsedCategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chargingBusiness', sa.String(length=255), nullable=True),
    sa.Column('userEmail', sa.String(length=255), nullable=True),
    sa.Column('targetCategoryId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['targetCategoryId'], ['userCategory.id'], ),
    sa.ForeignKeyConstraint(['userEmail'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurringTransactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userEmail', sa.String(length=255), nullable=True),
    sa.Column('transactionId', sa.String(), nullable=False),
    sa.Column('transactionName', sa.String(length=50), nullable=True),
    sa.Column('frequencyValue', sa.Integer(), nullable=True),
    sa.Column('frequencyUnit', sa.String(length=50), nullable=True),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('scannedAt', sa.DateTime(), nullable=True),
    sa.Column('iconName', sa.String(length=50), nullable=True),
    sa.Column('colorCode', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['transactionId'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['userEmail'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurringTransactions')
    op.drop_table('userParsedCategory')
    op.drop_index(op.f('ix_userCategorySpending_date'), table_name='userCategorySpending')
    op.drop_table('userCategorySpending')
    op.drop_table('transaction')
    op.drop_table('categoryMonthlyAveragesHistory')
    op.drop_table('userWarnings')
    op.drop_table('userCategory')
    op.drop_table('appUserCredentials')
    op.drop_table('user')
    # ### end Alembic commands ###
