"""Replaced the uid column with the authorizationNumber column in transactions table

Revision ID: 2f95f19c32d5
Revises: 4a042ae904f1
Create Date: 2023-11-30 13:34:42.703557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f95f19c32d5'
down_revision: Union[str, None] = '4a042ae904f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('authorizationNumber', sa.String(), nullable=True))
    op.drop_column('transaction', 'uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'authorizationNumber')
    # ### end Alembic commands ###
