"""Added currency column to users table

Revision ID: 34134247b29e
Revises: 3f3388de553a
Create Date: 2023-11-14 18:38:13.992940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34134247b29e'
down_revision: Union[str, None] = '3f3388de553a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currency', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'currency')
    # ### end Alembic commands ###
