from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3f2b3238865b'
down_revision = 'f5b2509e9d01'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "appUserCredentials" ALTER COLUMN password TYPE BYTEA USING password::bytea')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add appropriate downgrade logic if necessary
    op.execute('ALTER TABLE "appUserCredentials" ALTER COLUMN password TYPE VARCHAR USING password::VARCHAR')
    # ### end Alembic commands ###
