"""Added autoincrement to UserWarnings id

Revision ID: 456f88d22d31
Revises: 1bbb11937a66
Create Date: 2023-10-28 17:37:07.369013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456f88d22d31'
down_revision: Union[str, None] = '1bbb11937a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
