"""Added userEmail column to recurring transactionstable

Revision ID: 46defd85473e
Revises: 16f72c86cc5c
Create Date: 2023-11-15 12:53:55.129545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46defd85473e'
down_revision: Union[str, None] = '16f72c86cc5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurringTransactions', sa.Column('userEmail', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'recurringTransactions', 'user', ['userEmail'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recurringTransactions', type_='foreignkey')
    op.drop_column('recurringTransactions', 'userEmail')
    # ### end Alembic commands ###
