"""Added uid column to Transactions table

Revision ID: c0f3dee87af7
Revises: 5e010f8cf6f2
Create Date: 2023-11-27 11:55:37.027783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f3dee87af7'
down_revision: Union[str, None] = '5e010f8cf6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('uid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'uid')
    # ### end Alembic commands ###
