"""Added Icon/Color fields to category and recurring transaction tables, added isDeleted field to transaction and fixed naming convention in recurringTransactions table

Revision ID: d71e8e1190d9
Revises: 456f88d22d31
Create Date: 2023-11-07 15:23:38.851074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71e8e1190d9'
down_revision: Union[str, None] = '456f88d22d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('iconName', sa.String(length=50), nullable=True))
    op.add_column('category', sa.Column('colorCode', sa.String(length=50), nullable=True))
    op.add_column('recurringTransactions', sa.Column('transactionId', sa.String(), nullable=False))
    op.add_column('recurringTransactions', sa.Column('frequencyValue', sa.Integer(), nullable=True))
    op.add_column('recurringTransactions', sa.Column('frequencyUnit', sa.String(length=50), nullable=True))
    op.add_column('recurringTransactions', sa.Column('iconName', sa.String(length=50), nullable=True))
    op.add_column('recurringTransactions', sa.Column('colorCode', sa.String(length=50), nullable=True))
    op.drop_constraint('recurringTransactions_transaction_id_fkey', 'recurringTransactions', type_='foreignkey')
    op.create_foreign_key(None, 'recurringTransactions', 'transaction', ['transactionId'], ['id'])
    op.drop_column('recurringTransactions', 'frequency_unit')
    op.drop_column('recurringTransactions', 'transaction_id')
    op.drop_column('recurringTransactions', 'frequency_value')
    op.add_column('transaction', sa.Column('isDeleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'isDeleted')
    op.add_column('recurringTransactions', sa.Column('frequency_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('recurringTransactions', sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('recurringTransactions', sa.Column('frequency_unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recurringTransactions', type_='foreignkey')
    op.create_foreign_key('recurringTransactions_transaction_id_fkey', 'recurringTransactions', 'transaction', ['transaction_id'], ['id'])
    op.drop_column('recurringTransactions', 'colorCode')
    op.drop_column('recurringTransactions', 'iconName')
    op.drop_column('recurringTransactions', 'frequencyUnit')
    op.drop_column('recurringTransactions', 'frequencyValue')
    op.drop_column('recurringTransactions', 'transactionId')
    op.drop_column('category', 'colorCode')
    op.drop_column('category', 'iconName')
    # ### end Alembic commands ###
