"""Added isPending column to Transactions table

Revision ID: d73c7492e49d
Revises: c0f3dee87af7
Create Date: 2023-11-27 15:43:46.620061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73c7492e49d'
down_revision: Union[str, None] = 'c0f3dee87af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('isPending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'isPending')
    # ### end Alembic commands ###
