"""Added a fullName field to the users table

Revision ID: f200eef5fe5f
Revises: 1311cd767114
Create Date: 2023-11-08 18:59:44.091020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f200eef5fe5f'
down_revision: Union[str, None] = '1311cd767114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullName', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fullName')
    # ### end Alembic commands ###
