"""Changed merchantData type from json to jsonb column in transactions table

Revision ID: f5b2509e9d01
Revises: 2f95f19c32d5
Create Date: 2023-12-01 14:48:33.235709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b2509e9d01'
down_revision: Union[str, None] = '2f95f19c32d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
